### ISSUE TITLE
Not backing up mounted subfolders since tag "1.8.2-1.2.6"

### ISSUE THREAD

**Issue by mrclschstr** [modem7/docker-borgmatic#125]
I'll try to describe my problem, which unfortunately is not easy for me, but I'll try my best 😃 I back up my Nextcloud instance with the borgmatic container and have packed the important folders into individual volumes. I mount these volumes under the folder `/mnt/source` in the borgmatic container in individual subfolders. Here is an excerpt from the `docker-compose.yml`:

```yaml
volumes:
  - nextcloud-custom_apps:/mnt/source/custom_apps
  - nextcloud-config:/mnt/source/config
  - nextcloud-data:/mnt/source/data
  - nextcloud-themes:/mnt/source/themes
```

Previously it was sufficient to simply specify the `/mnt/source` folder in `config.yaml`, here is an excerpt:

```yaml
source_directories:
  - /mnt/source
```

Starting with the image tag `1.8.2-1.2.6` this unfortunately no longer works. **The files in the individual subfolders are no longer backed up** and the backups are therefore unusable. As a workaround, I now back up each subfolder individually (excerpt from `config.yaml`):

```yaml
# WORKAROUND
source_directories:
  - /mnt/source/custom_apps
  - /mnt/source/config
  - /mnt/source/data
  - /mnt/source/themes
```

As I have already written, the problem only exists since the image tag `1.8.2-1.2.6` and with `1.8.2-1.2.5` everything still works as expected. I have not found anything in the borg release notes that would indicate this bug and since the borgmatic version has not changed between releases, I would rule out a bug there. Can you help me to identify the error? Is this an intended behavior?

**Comment by modem7** [comment]
What errors are you seeing in the logs?

Are you able to see the folders when you enter the container via `docker exec -it Borgmatic /bin/bash`?

**Comment by mrclschstr** [comment]
> What errors are you seeing in the logs?
None, the backup finishes without errors. That's also pretty nasty behavior, since that's why I didn't realize that my backups have been unusable since mid-September.

> Are you able to see the folders when you enter the container via `docker exec -it Borgmatic /bin/bash`?
Yes, I already checked that. I can see the folders itself with all the files within.

**Comment by modem7** [comment]
It may be worthwhile posting on the [original repo](https://github.com/borgmatic-collective/docker-borgmatic/issues) so the project maintainer (Witten and co) can have a look. This is mostly a fork with a few custom bits, so I can only answer to most of the Docker problems rather than the Borg(matic) issues themselves.

**Comment by mrclschstr** [comment]
Unfortunately, the problem still exists with the tag `1.8.5-1.2.6`.

I will have a look at the original container and open an issue there as well.

**Comment by mrclschstr** [comment]
I just tested my environment with the latest container `ghcr.io/borgmatic-collective/borgmatic:1.8.4` and the **backups work without problems**, even if I only specify `/mnt/source` under `source_directories` in the borgmatic `config.yaml`.

I suspect that the problem exists only with your container, but I have no real explanation for it. I don't want to rule out that I'm making a mistake, but I can`t see the forest for the trees.

Let me prepare a minimal example. Maybe we can use it to better understand the problem.

**Comment by mrclschstr** [comment]
Oops, I accidentally closed this issue... sorry!

**Comment by modem7** [comment]
Sounds like a plan.

If we can figure out a basic compose file with volume mounts, we can figure out potential issues, especially as we'll be implementing a lot of the changes in this repo to the upstream (like s6), so it'd be good to understand why this is occurring.

**Comment by modem7** [comment]
Just for transparency, this is my config:

```yaml
  borgmatic:
    image: modem7/borgmatic-docker
    # image: borgmatic:test
    container_name: Borgmatic
    environment:
      TZ: $TZ
      BORG_PASSPHRASE: $BORG_PASSPHRASE
      BORG_SOURCE_1: $BORG_SOURCE_1
      BORG_SOURCE_2: $BORG_SOURCE_2
      BORG_REPO: $BORG_REPO
      BORG_HEALTHCHECK_URL: $BORG_HEALTHCHECK_URL
      CRON: $BORG_CRON
      DOCKERCLI: true
      CRON_COMMAND: $BORG_CRON_COMMAND
      # EXTRA_CRON: |-
      #   0 5 2 * * command1
      #   0 7 1 * * command2
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - $BORGHOMESOURCEDIR:/mnt/source/
      # - $CRONTAB:/mnt/source/Cron
      # - Pihole:/mnt/source/Pihole/Pihole
      # - Dnsmasq:/mnt/source/Pihole/Dnsmasq
      - $BORGSERVBACKUPDIR/Database:/mnt/borg-DBrepository
      - $BORGSERVBACKUPDIR/Docker:/mnt/borg-repository
      - $RAMDRIVEBACKUP/borg:/mnt/ramdrive
      - $USERDIR:/mnt/source/DockerApps/
      - $USERDIR/Borgmatic/borgmatic.d/:/etc/borgmatic.d/
      - $USERDIR/Borgmatic/.config/borg/:/root/.config/borg
      - $USERDIR/Borgmatic/.ssh/:/root/.ssh
      - $USERDIR/Borgmatic/.state/:/root/.borgmatic
      - $USERDIR/Borgmatic/.cache/borg/:/root/.cache/borg
      - $BORGSCRIPTS:/borgscripts
      - /var/run/docker.sock:/var/run/docker.sock # So we can run scripts
    networks:
      isonet:
      isolated:
    restart: always
```

.env
```
# Borgmatic
BORGSERVBACKUPDIR="/mnt/oldhd/ServerBackup/"
BORGHOMESOURCEDIR="/home/alex/"
CRONTAB="/var/spool/cron/"
BORGSCRIPTS="/home/alex/DockerApps/Borgmatic/scripts/"
BORG_PASSPHRASE="passphrase"
BORG_RESTORE="/mnt/downloads/"
#BORG_RESTORE="/var/hda/files/drives/drive12/downloads/"
BORG_REPO="ssh://reponame.repo.borgbase.com/./repo"
BORG_SOURCE_1="/mnt/source/DockerApps"
BORG_SOURCE_2="/mnt/source/Cron"
BORG_HEALTHCHECK_URL="https://hc-ping.com/uuid"
BORG_CRON="0 5 * * *"
BORG_CRON_COMMAND="borgmatic --stats -v 0"
```

borgmatic config:
```yaml
source_directories:
     - ${BORG_SOURCE_1}
     - ${BORG_SOURCE_2}
repositories:
     - path: ${BORG_REPO}
       label: Borgbase
one_file_system: true
exclude_caches: true

#storage:
#   Passphase is set in variable $BORG_PASSPHRASE
compression: lz4
archive_name_format: 'backup-{now}'

keep_hourly: 0
keep_daily: 7
keep_weekly: 4
keep_monthly: 12
keep_yearly: 1

checks:
  - name: repository
    frequency: 2 weeks
  - name: archives
    frequency: always
  - name: extract
    frequency: 2 weeks
  - name: data
    frequency: 1 month

before_everything:
    - borgmatic break-lock
    - echo "Starting a backup job."
    - echo "Stopping containers."
    - exec /borgscripts/docker-stop.sh
after_everything:
    - echo "Starting containers."
    - exec /borgscripts/docker-start.sh
    - echo "Backup created."
on_error:
    - echo "Error while creating a backup."
    - exec /borgscripts/docker-start.sh
    # https://torsion.org/borgmatic/docs/how-to/backup-your-databases/

healthchecks:
    ping_url: ${BORG_HEALTHCHECK_URL}
```
