### ISSUE TITLE
Borg prune failing after udpate

### ISSUE THREAD

**Issue by zjean** [modem7/docker-borgmatic#92]
Hi, 
thanks for this great docker image. I am happy with it. 
Yesterday I pulled the latest docker image, and my backup stopped working.
```
usage: borg prune [-h] [--critical] [--error] [--warning] [--info] [--debug]

                  [--debug-topic TOPIC] [-p] [--iec] [--log-json]

                  [--lock-wait SECONDS] [--bypass-lock] [--show-version]

                  [--show-rc] [--umask M] [--remote-path PATH]

                  [--remote-ratelimit RATE] [--upload-ratelimit RATE]

                  [--remote-buffer UPLOAD_BUFFER]

                  [--upload-buffer UPLOAD_BUFFER] [--consider-part-files]

                  [--debug-profile FILE] [--rsh RSH] [-n] [--force] [-s]

                  [--list] [--keep-within INTERVAL] [--keep-last SECONDLY]

                  [--keep-minutely MINUTELY] [-H HOURLY] [-d DAILY]

                  [-w WEEKLY] [-m MONTHLY] [-y YEARLY] [-P PREFIX | -a GLOB]

                  [--save-space] [-c SECONDS]

                  [REPOSITORY]

borg prune: error: argument -a/--glob-archives: There can be only one.

/mnt/borg-repository: Error running actions for repository

Command 'borg prune --keep-hourly 2 --keep-daily 7 --keep-weekly 4 --keep-monthly 12 --keep-yearly 10 --glob-archives backup-* --glob-archives borgmatic-backup-* --stats /mnt/borg-repository' returned non-zero exit status 2.

Error while creating a backup.

/etc/borgmatic.d/config.yaml: An error occurred
```

This is the location excerpt of my config.yaml
```
location:
    source_directories:
        - /mnt/source
    
    exclude_patterns:
        - '*nextcloud/data/*/files_trashbin/*'
        - '*nextcloud/data/updater-*/backups/*'
      
    repositories:
        - /mnt/borg-repository
```

Did I do something wrong in my config?
Thanks!
